[spf]layer_001: typos and error handling

diff --git a/spf/layer_001/layer_001 b/spf/layer_001/layer_001
--- a/spf/layer_001/layer_001
+++ b/spf/layer_001/layer_001
@@ -1,6 +1,7 @@
 #!/bin/bash
 
-typing_speed=13
+typing_speed=15
+log_file="$HOME/lab1_err"
 
 choice=0
 where_are_you=1
@@ -13,26 +14,38 @@ leave=6
 trap goodbye INT
 
 function say {
-  echo "$1" | pv -qL $typing_speed
+  if [ $NOTYPE -eq "1" ]; then
+    echo "$1"
+  else
+    echo "$1" | pv -qL $typing_speed
+  fi
 }
 
 function ask {
-  echo $1 | pv -qL $typing_speed
-  read $2 || exit
+  if [ $NOTYPE -eq "1" ]; then
+    echo "$1"
+  else
+    echo $1 | pv -qL $typing_speed
+  fi
+  read $2 || goodbye
+}
+
+function handle_error {
+  echo $1 1>&2
 }
 
 function the_offer {
   say "--- Hello "$USER"! ---"
   echo
-  say "This is extremely powerfull script,"
+  say "This is extremely powerful script,"
   say "and you are free to choose one of"
   say "the options below:"
   echo
-  say "  -- 1 to find out where are you"
+  say "  -- 1 to find out where you are"
   say "  -- 2 to see what is here"
   say "  -- 3 to create a new place"
   say "  -- 4 to travel to a place"
-  say "  -- 5 to destroy the place"
+  say "  -- 5 to destroy a place"
   say "  -- 6 to leave"
   echo
   ask "So, what would it be?" choice
@@ -40,21 +53,25 @@ function the_offer {
 }
 
 function where_are_you_func {
-  say "You want to know where are you?"
+  say "You want to know where you are?"
   say "You are in "$PWD""
   echo
 }
 
 function what_is_here_func {
   say "You want to know what is here? There is:"
-  ls | pv -qL $typing_speed
+  if [ $NOTYPE -eq "1" ]; then
+    ls
+  else
+    ls | pv -qL $typing_speed
+  fi
   echo
 }
 
 function create_place_func {
   say "You want to create a new place? Then you need to give it a name"
   ask "Enter the name of the new place:" dir_name
-  mkdir -p $dir_name
+  mkdir -p $dir_name 2>>$log_file | handle_error "Cannot create a place, please check the permissions"
   say "$dir_name created!"
   echo
 }
@@ -62,7 +79,7 @@ function create_place_func {
 function travel_func {
   say "You want to travel? Then you need to set a destination"
   ask "Enter the destination name:" destination
-  cd $destination
+  cd $destination 2>>$log_file | handle_error "Cannot travel, check if the place exists"
   say "Now we are in "$PWD"!"
   echo
 }
@@ -70,7 +87,7 @@ function travel_func {
 function destroy_func {
   say "You want to destroy some place?"
   ask "What place do you want to destroy?" destination
-  rm -ri $destination
+  rm -ri $destination 2>>$log_file | handle_error "Cannot destroy, check if place exists"
   echo
 }
 
